### ISSUE TITLE
Invalid request body. Please refer to the documentation.

### ISSUE THREAD

**Issue by AndreiD** [Ontotext-AD/S4#1]
Hello

I have endpointUrl = "https://text.s4.ontotext.com/v1/news";

Using the demo account. It works for smaller texts. but for some of them I get (400 error code) Invalid request body. Please refer to the documentation.

Example:

*** REST API. *** 

~~~~
{"document":"Practical over the course of several centuries with fracking about Battlestar Galactica get me from the past all live there are so many great things in your future tiny Spain's influence spread around the world and she's the wise of almost every human on the planet generally a negative way sign a crash course recently the 16th century people are getting richer the more connected lives all I can do is one about a much better the old days were one of your grandpa will confess to you. America that on or we go to the whole matter the Mayans but they were probably the greatest she has text. The three major cities in modern-day Mexico in about 1430 just 89 years before Cortes and his conquistador showed up yes it was very hierarchical with Amber at the top of the group of unruly nobles but. Powerful priests his job was to keep ordering the cosmos you know history was cyclical and punctuated by terrible disasters and that would ultimately end with a massive apocalypse drop the price was to avoid these disasters by appeasing the guns generally through human sacrifice CSX. Guatemalan the Yucatán and he demanded tribute from Concord people in the form of goods precious metals and people to sacrifice. Like venison that it was divided in service by canals deals with floating gardens coaching office which provided food for the city","documentType":"text\/plain"}
~~~~

--------

I searched the documentation but I couldn't find any info on restrictions etc. I think I'm doing something wrong but I don't know what.

#### Any thoughts on this ?

**Comment by marin-dim** [comment]
hi Andrey,

there's no limit of the size of the documents processed by S4

I just processed your sample document and this is what I got:

+++++++++++++++++++++
{
  "text": "Practical over the course of several centuries with fracking about Battlestar Galactica get me from the past all live there are so many great things in your future tiny Spain's influence spread around the world and she's the wise of almost every human on the planet generally a negative way sign a crash course recently the 16th century people are getting richer the more connected lives all I can do is one about a much better the old days were one of your grandpa will confess to you. America that on or we go to the whole matter the Mayans but they were probably the greatest she has text. The three major cities in modern-day Mexico in about 1430 just 89 years before Cortes and his conquistador showed up yes it was very hierarchical with Amber at the top of the group of unruly nobles but. Powerful priests his job was to keep ordering the cosmos you know history was cyclical and punctuated by terrible disasters and that would ultimately end with a massive apocalypse drop the price was to avoid these disasters by appeasing the guns generally through human sacrifice CSX. Guatemalan the Yucatán and he demanded tribute from Concord people in the form of goods precious metals and people to sacrifice. Like venison that it was divided in service by canals deals with floating gardens coaching office which provided food for the city",
  "entities": {
    "Sentence": [
      {
        "indices": [
          0,
          486
        ],
        "type": "Sentence",
        "string": "Practical over the course of several centuries with fracking about Battlestar Galactica get me from the past all live there are so many great things in your future tiny Spain's influence spread around the world and she's the wise of almost every human on the planet generally a negative way sign a crash course recently the 16th century people are getting richer the more connected lives all I can do is one about a much better the old days were one of your grandpa will confess to you."
      },
      {
        "indices": [
          487,
          592
        ],
        "type": "Sentence",
        "string": "America that on or we go to the whole matter the Mayans but they were probably the greatest she has text."
      },
      {
        "indices": [
          593,
          795
        ],
        "type": "Sentence",
        "string": "The three major cities in modern-day Mexico in about 1430 just 89 years before Cortes and his conquistador showed up yes it was very hierarchical with Amber at the top of the group of unruly nobles but."
      },
      {
        "indices": [
          796,
          1080
        ],
        "type": "Sentence",
        "string": "Powerful priests his job was to keep ordering the cosmos you know history was cyclical and punctuated by terrible disasters and that would ultimately end with a massive apocalypse drop the price was to avoid these disasters by appeasing the guns generally through human sacrifice CSX."
      },
      {
        "indices": [
          1081,
          1209
        ],
        "type": "Sentence",
        "string": "Guatemalan the Yucatán and he demanded tribute from Concord people in the form of goods precious metals and people to sacrifice."
      },
      {
        "indices": [
          1210,
          1340
        ],
        "type": "Sentence",
        "string": "Like venison that it was divided in service by canals deals with floating gardens coaching office which provided food for the city"
      }
    ],
    "Location": [
      {
        "indices": [
          169,
          174
        ],
        "type": "Location",
        "ambiguityRankWithinClass": 1,
        "inst": "http://sws.geonames.org/2510769/",
        "class": "http://www.ontotext.com/proton/protontop#Location",
        "string": "Spain",
        "id": 109,
        "tokenFeature": "string",
        "countryCode": [
          "ES"
        ],
        "uiRepresentation": [
          "Geolocation"
        ],
        "featCode": [
          "http://www.geonames.org/ontology#A.PCLI"
        ],
        "featClass": [
          "http://www.geonames.org/ontology#A"
        ],
        "isTrusted": "true",
        "confidence": 0.9999999999998358,
        "ambiguityRank": 2
      },
      {
        "indices": [
          487,
          494
        ],
        "type": "Location",
        "ambiguityRankWithinClass": 1,
        "inst": "http://sws.geonames.org/6252001/",
        "class": "http://www.ontotext.com/proton/protontop#Location",
        "string": "America",
        "id": 117,
        "tokenFeature": "string",
        "uiRepresentation": [
          "Geolocation"
        ],
        "featCode": [
          "http://www.geonames.org/ontology#A.PCLI"
        ],
        "featClass": [
          "http://www.geonames.org/ontology#A"
        ],
        "countryCode": [
          "US"
        ],
        "isTrusted": "true",
        "confidence": 0.999999999782756,
        "ambiguityRank": 12
      },
      {
        "indices": [
          630,
          636
        ],
        "type": "Location",
        "ambiguityRankWithinClass": 2,
        "inst": "http://sws.geonames.org/3996063/",
        "class": "http://www.ontotext.com/proton/protontop#Location",
        "string": "Mexico",
        "id": 85,
        "tokenFeature": "string",
        "countryCode": [
          "MX"
        ],
        "uiRepresentation": [
          "Geolocation"
        ],
        "featCode": [
          "http://www.geonames.org/ontology#A.PCLI"
        ],
        "featClass": [
          "http://www.geonames.org/ontology#A"
        ],
        "isTrusted": "true",
        "confidence": 0.9999999856927583,
        "ambiguityRank": 4
      },
      {
        "indices": [
          1133,
          1140
        ],
        "type": "Location",
        "ambiguityRankWithinClass": 5,
        "inst": "http://dbpedia.org/resource/Concord,_New_Hampshire",
        "class": "http://www.ontotext.com/proton/protontop#Location",
        "string": "Concord",
        "id": 29839,
        "tokenFeature": "string",
        "uiRepresentation": [
          "Geolocation"
        ],
        "featClass": [
          "http://www.geonames.org/ontology#P"
        ],
        "countryCode": [
          "US"
        ],
        "featCode": [
          "http://www.geonames.org/ontology#P.PPLA"
        ],
        "isTrusted": "true",
        "confidence": 0.9999852610180255,
        "ambiguityRank": 7
      }
    ],
    "Organization": [
      {
        "indices": [
          1076,
          1079
        ],
        "type": "Organization",
        "ambiguityRankWithinClass": 0,
        "ambiguityRank": 0,
        "inst": "http://data.ontotext.com/publishing/organization/CSX",
        "string": "CSX",
        "class": "http://www.ontotext.com/proton/protontop#Organization",
        "isGenerated": "true"
      }
    ],
    "Keyphrase": [
      {
        "indices": [
          777,
          790
        ],
        "type": "Keyphrase",
        "isGenerated": "true",
        "class": "http://www.ontotext.com/proton/protontop#Topic",
        "inst": "http://data.ontotext.com/publishing/topic/Unruly_noble",
        "rule": "FixOverlaps",
        "string": "Unruly noble",
        "lemmatizedForm": "Unruly noble",
        "tfidf": 0.7180513467203118,
        "length": "2",
        "tfIdfDisc": "14",
        "rightNo": 93,
        "leftNo": 149,
        "elemNo": 2,
        "mllabel": "Pos = 1.28125&Neg = -1.28125",
        "label": "Pos",
        "confidence": 0.9284088005554475
      },
      {
        "indices": [
          1081,
          1091
        ],
        "type": "Keyphrase",
        "isGenerated": "true",
        "class": "http://www.ontotext.com/proton/protontop#Topic",
        "inst": "http://data.ontotext.com/publishing/topic/Guatemalan",
        "rule": "FixOverlaps",
        "string": "Guatemalan",
        "lemmatizedForm": "Guatemalan",
        "tfidf": 0.7547656034750799,
        "length": "1",
        "tfIdfDisc": "15",
        "rightNo": 43,
        "leftNo": 200,
        "elemNo": 1,
        "mllabel": "Pos = 2.71875&Neg = -2.71875",
        "label": "Pos",
        "confidence": 0.995668497979436
      },
      {
        "indices": [
          1323,
          1327
        ],
        "type": "Keyphrase",
        "isGenerated": "true",
        "class": "http://www.ontotext.com/proton/protontop#Topic",
        "inst": "http://data.ontotext.com/publishing/topic/Food",
        "rule": "FixOverlaps",
        "string": "Food",
        "lemmatizedForm": "Food",
        "tfidf": 0.22580890001481788,
        "length": "1",
        "tfIdfDisc": "4",
        "rightNo": 3,
        "leftNo": 240,
        "elemNo": 1,
        "mllabel": "Pos = 0.875&Neg = -0.875",
        "label": "Pos",
        "confidence": 0.8519528019683106
      }
    ],
    "Person": [
      {
        "indices": [
          67,
          87
        ],
        "type": "Person",
        "ambiguityRankWithinClass": 0,
        "ambiguityRank": 0,
        "inst": "http://data.ontotext.com/publishing/person/Battlestar_Galactica",
        "string": "Battlestar Galactica",
        "class": "http://www.ontotext.com/proton/protontop#Person",
        "isGenerated": "true"
      }
    ]
  },
  "keyphrasesTfIdf": [
    "Yucatán",
    "Human sacrifice CSX",
    "Conquistador",
    "Grandpa",
    "Venison"
  ]
}
+++++++++++++++++++++

can you provide more details about the problems?

**Comment by AndreiD** [comment]
Seems to work now for that text, but..... there's another error now

for 

~~~~
{"document":"Chronology of the American Revolution and you my graphical details about Thomas Jefferson or George Washington. Get mean not wearing any pants. Planted and was Joel guided me for the best all it's fun to focus on metaphorically resident details what. The American Revolution happened in the extent to which it was","documentType":"text/plain"}
~~~~

I get request timed out


java.net.SocketTimeoutException: Read timed out
W/System.err﹕ at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:728)
W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)

**Comment by AndreiD** [comment]
note: this only happens from time to time. I would say 1/10.

**Comment by Yadp** [comment]
We fixed the problem. Now everything works fine
